### PR TITLE
[core]delete created_from_snapshot and created_from_snapshot from branchTable

### PR DESCRIPTION
**Pull request by herefree**
### Purpose

`created_from_snapshot` should be the origin of the tag,not the earliest snapshot of the branch.

Linked issue: close #xxx

### CODE REVIEW

**Comment by LinMingQiang** [comment]
It is possible that the branches tag does not exist but the snapshot exists?

**Comment by herefree** [comment]
> It is possible that the branches tag does not exist but the snapshot exists?

Yes, if you create empty branch then insert some data to this branch, or you create branch from tag then delete branch's tag. In above two case snapshot will exists,tag will not exists. In this case created_from_tag will be null. 
I do not think we should remain created_from_snapshot,because we only support create_branch from tag. Snapshot will expire quickly, it's hard for us to know whether the earliest snapshot of the branch is from the main branch.

**Comment by LinMingQiang** [comment]
`created_from_snapshot` can be the origin of the tag?

**Comment by herefree** [comment]
> `created_from_snapshot` can be the origin of the tag?

That's okay, I'll modify it.

**Comment by LinMingQiang** [comment]
With the current architecture, we cannot accurately obtain the origin snapshot of the branch. Maybe we should open a discussion thread to discuss this issue.

**Comment by herefree** [comment]
> With the current architecture, we cannot accurately obtain the origin snapshot of the branch. Maybe we should open a discussion thread to discuss this issue.

I create a issue #4166

**Comment by JingsongLi** [comment]
Can we just delete created_from_tag and created_from_snapshot first?

**Comment by herefree** [comment]
> Can we just delete created_from_tag and created_from_snapshot first?

I think it's ok if we can't get the exact tag and snapshot.I'll change it.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
