### PR TITLE
[spark] show table extended

### PR DESCRIPTION
**Pull request by YannByron**
### Purpose

to support `SHOW TABLE EXTENDED ((FROM | IN) ns=identifierReference)? LIKE pattern=stringLit partitionSpec?` syntax.

Linked issue: close #xxx

### CODE REVIEW

**Comment by xuzifu666** [comment]
Nice Job，seems SparkSQL had not supported with the v2 syntax yet.

**Comment by xuzifu666** [comment]
+1， left some minor comments.

**Comment by YannByron** [comment]
> Nice Job，seems SparkSQL had not supported with the v2 syntax yet.

Spark supports it for v2 table in 4.x. So I just need do this for spark 3.x.

**Comment by YannByron** [comment]
> Thanks @YannByron , Can you also modify documentation?

added.

**Review by xuzifu666 — APPROVED** [review]
+1

**Pull request merged**
