### PR TITLE
[Core]Fix Flink batch reads the paimon partition table jobManager oom

### LINKED ISSUE #3240: [Feature] Flink batch reads the paimon partition table jobManager oom and optimizes its partition scanning
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

After adding SHOW Partitions commit in version 0.6 of Paymon, the current implementation involves scanning all files and retrieving partition information, using ManifestEntry, which contains a large amount of information. When there are too many table partitions and files, it can cause JobManager ooms. Because it is necessary to simplify the implementation of listPartition. The current production issue we are facing is upgrading from paymon0.6 to 0.8. Previously, JobManager provided 10g of memory without any issues, but now we need to provide it to 80-100g If the log is typed in the code and the listPartition scans all the information, there will be 150w Splits. But normal scanning queries usually come with a partitionFilter, which 1w splits per day.
image
image

### Solution

There are several solutions:
1. When returning to the previous version of ListPartition(), Collections. emptyList() was returned. However, this temporary solution still needs to be implemented to support the show partitions of Flink 1.18.
2. Add the implementation of listPartition and scan data separately for the partition.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by BeiWeiDeDengDai**
### Purpose

Linked issue: close #3240 

### Optimize Partition Scanning
 Improve the speed of scanning partitions in FlinkCatalog listPartitions to avoid reading a large number of ManifestEntries that could cause JobManager ooms, 
image

### CODE REVIEW

**Comment by JingsongLi** [comment]
You can try:

## SnapshotReaderImpl
```
    @Override
    public List<BinaryRow> partitions() {
        List<ManifestEntry> entryList = scan.plan().files();

        return entryList.stream()
                .collect(
                        Collectors.groupingBy(
                                ManifestEntry::partition,
                                LinkedHashMap::new,
                                Collectors.reducing((a, b) -> b)))
                .values()
                .stream()
                .map(Optional::get)
                .map(ManifestEntry::partition)
        return scan.readSimpleEntries().stream()
                .map(SimpleFileEntry::partition)
                .distinct()
                .collect(Collectors.toList());
    }
```

## FlinkCatalog
```
            ReadBuilder readBuilder = table.newReadBuilder();
            if (partitionSpec != null && partitionSpec.getPartitionSpec() != null) {
                readBuilder.withPartitionFilter(partitionSpec.getPartitionSpec());
            }

            List<BinaryRow> partitions = readBuilder.newScan().listPartitions();
```

**Comment by BeiWeiDeDengDai** [comment]
I tried it and it was also possible
`return scan.readSimpleEntries().stream()
                .map(SimpleFileEntry::partition)
                .distinct()
                .collect(Collectors.toList());`

**Comment by BeiWeiDeDengDai** [comment]
I deleted the previously added readPartitions section and directly used scan.plan().files()

**Comment by JingsongLi** [comment]
+1

**Pull request merged**
