### PR TITLE
[Flink]Add flink action for creating and deleting branch

### PR DESCRIPTION
**Pull request by herefree**
### Purpose

subtask of https://github.com/apache/incubator-paimon/issues/1795

### Tests
org.apache.paimon.flink.action.BranchActionITCase#testCreateAndDeleteBranch

## Delete Branch

You can delete a branch by its name.

Run the following command:

```bash
<FLINK_HOME>/bin/flink run \
    /path/to/paimon-flink-action.jar \
    delete_branch \
    --warehouse <warehouse-path> \
    --database <database-name> \ 
    --table <table-name> \
    --branch_name <branch-name> \
    [--catalog_conf <paimon-catalog-conf> [--catalog_conf <paimon-catalog-conf> ...]]
```

## Create Branch

You can create a branch with given name and tag name.
Run the following command:

```bash
<FLINK_HOME>/bin/flink run \
    /path/to/paimon-flink-action.jar \
    create_branch \
    --warehouse <warehouse-path> \
    --database <database-name> \ 
    --table <table-name> \
    --branch_name <branch-name> \
    --tag_name <tag-name> \
    [--catalog_conf <paimon-catalog-conf> [--catalog_conf <paimon-catalog-conf> ...]]
```

### CODE REVIEW

**Comment by herefree** [comment]
@TaoZex @FangYongs help review thanks~

**Comment by TaoZex** [comment]
Please add the corresponding content in the doc.

**Comment by herefree** [comment]
@TaoZex I added some comments above, do you think this is okay?

**Comment by schnappi17** [comment]
@herefree We can create a doc to guide `Manage Branches`, you can see `Manage Tags`.

**Pull request closed without merging**
