### PR TITLE
[spark] Delete with deletion vectors should enable AQE

### PR DESCRIPTION
**Pull request by ulysses-you**
### Purpose

AQE won't break the required distribution and ordering, so it is unnecessary to disable aqe manually.

### Tests

Pass CI

### API and Format

no

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @JingsongLi @YannByron thank you

**Comment by YannByron** [comment]
Disabling AQE will have a better performance when performing delete operations with DV on large amounts of data,
but it can submit more tasks in other cases. Paimon can ignore this, and left to users to tune.

**Comment by YannByron** [comment]
+1

**Comment by JingsongLi** [comment]
+1

**Pull request merged**
