### PR TITLE
[core] Add immutable id for system field 

### PR DESCRIPTION
**Pull request by Zouxxyy**
### Purpose

Field id should not be changed at any time

- Add immutable id for system field
- Make all fileds immutable even in calculating internally

Preparation for #4209

### CODE REVIEW

**Comment by JingsongLi** [comment]
Thanks @Zouxxyy for the contribution.

I just want to figure out what is the impact of this PR? Does it affect the storage?

**Comment by Zouxxyy** [comment]
> I just want to figure out what is the impact of this PR? Does it affect the storage?

no，these system field just used when computer, and not persist in schema(storage)

**Comment by Zouxxyy** [comment]
This PR is prepare for using rowType to replace projection, because I want rowType to be immutable.
And, in theory, the id of the field is unique and cannot be modified once written, because schema evolution is based on id

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
