### PR TITLE
[Flink]Supports SQLServer cdc

### PR DESCRIPTION
**Pull request by sunxiaojian**
### Purpose

Linked issue: close (https://github.com/apache/incubator-paimon/issues/2399)
  Add SQLServer cdc connector

### CODE REVIEW

**Comment by JingsongLi** [comment]
Thanks @sunxiaojian 

But I hardly ever hear of anyone wanting to use sqlserver cdc.

**Comment by sunxiaojian** [comment]
> Thanks @sunxiaojian
> 
> But I hardly ever hear of anyone wanting to use sqlserver cdc.

In fact, many government and enterprise users still use SQL Server and Oracle to store data, and the companies that provide them with data services require this feature

**Comment by sunxiaojian** [comment]
> Thanks @sunxiaojian
> 
> But I hardly ever hear of anyone wanting to use sqlserver cdc.

@JingsongLi In fact, many government and enterprise users still use SQL Server and Oracle to store data, and the companies that provide them with data services require this feature

**Comment by renxiaoyao** [comment]
So,  Where can I find the relevant code? I also developed SqlServer CDC Action and want to contribute to paimon.

**Comment by sunxiaojian** [comment]
> So, Where can I find the relevant code? I also developed SqlServer CDC Action and want to contribute to paimon.

@renxiaoyao Waiting for review   @JingsongLi  @yuzelin @zhuangchong PTAL

**Comment by cs3163077** [comment]
not support schema changes？

**Comment by sunxiaojian** [comment]
> not support schema changes？

Yes, the current version of sqlserver cdc is not supported yet, and data parsing errors will occur. I will continue to follow up, or contribute code to cdc to support this feature.

**Comment by sunxiaojian** [comment]
@JingsongLi @yuzelin If you have time, could you please help review it

**Pull request closed without merging**
