### PR TITLE
[flink] Add expire partitions procedure for flink.

### PR DESCRIPTION
**Pull request by LinMingQiang**
### Purpose

Linked issue: https://github.com/apache/paimon/issues/3434

### CODE REVIEW

**Comment by LinMingQiang** [comment]
@JingsongLi Do you have time to review this pr for me? thanks.

**Comment by leaves12138** [comment]
I think `TableCommitImpl` in paimon-core does not need to know if it is endInput, just need to know it should force expire.

**Comment by LinMingQiang** [comment]
Yeah,you were right,thanks for the advice.

**Comment by LinMingQiang** [comment]
@JingsongLi  Do you have time to review this pr for me? Thanks.

**Review by JingsongLi — CHANGES_REQUESTED** [review]
Hi @LinMingQiang , Partition filtering cannot be performed every endinput, it is a relatively heavy operation that is not conducive to smaller operations.

Can you consider having a CALL procedure and manually executing it?

**Comment by LinMingQiang** [comment]
Yes, I have considered this question before,performing partition filtering every time is a costly operation.  And i will try your advice.

**Comment by LinMingQiang** [comment]
@JingsongLi I add a procedure to execute expire partitions. cc

**Comment by leaves12138** [comment]
May flink 1.8 could use procedure in common

**Review by leaves12138 — APPROVED** [review]
+1

**Pull request merged**
