### PR TITLE
[doc] Update doc style

### PR DESCRIPTION
**Pull request by Edward-Gavin**
### Purpose

Linked issue: close #4449

Inspired by issue 4449 and `CloneActionITCase`, I update `clone-tables.md` style. Does anyone have any better suggestions?
### Tests

**no**
### API and Format

**no**

### Documentation

Update `docs/content/flink/clone-tables.md` and `docs/content/flink/expire-partition.md`.

### CODE REVIEW

**Comment by JingsongLi** [comment]
Hi @Edward-Gavin , thanks for the contribution.

But can you gather all minor doc or comment PRs? Creating too many fragmented PRs, all of which involve minor modifications to the document, can cost the reviewer's energy.

**Comment by Edward-Gavin** [comment]
> Hi @Edward-Gavin , thanks for the contribution.
> 
> But can you gather all minor doc or comment PRs? Creating too many fragmented PRs, all of which involve minor modifications to the document, can cost the reviewer's energy.

Thanks for your time and suggestion, I will commit all modifications that I find in this pr.

**Comment by wwj6591812** [comment]
+1

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
