### PR TITLE
[Spark]Spark support create and delete branch procedure

### PR DESCRIPTION
**Pull request by TaoZex**
### Purpose

issue ： (https://github.com/apache/incubator-paimon/issues/2728)
subtaks of https://github.com/apache/incubator-paimon/issues/1795

### CODE REVIEW

**Comment by TaoZex** [comment]
PTAL @FangYongs @yuzelin

**Comment by TaoZex** [comment]
Timeout in ci, please rerun it.

**Comment by TaoZex** [comment]
PTAL @yuzelin @FangYongs

**Comment by TaoZex** [comment]
Please have a look if you have free time @YannByron ,Thanks

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
