### PR TITLE
[core] rename file_size_in_bytes to total_file_size_in_bytes

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
### Purpose

rename file_size_in_bytes to total_file_size_in_bytes.

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
cc @JingsongLi

**Comment by JingsongLi** [comment]
Hi @MonsterChenzhuo , maybe it is better to just use bytes, this is SQL, if we return a string with special format, it is hard to use SQL to handle this type.

**Comment by MonsterChenzhuo** [comment]
> Hi @MonsterChenzhuo , maybe it is better to just use bytes, this is SQL, if we return a string with special format, it is hard to use SQL to handle this type.

Is it reasonable to keep file_size_in_bytes in $files since it's a base table, but add data_size to $partitions?

**Comment by JingsongLi** [comment]
Maybe just rename `file_size_in_bytes` to `total_file_size_in_bytes`?

**Comment by MonsterChenzhuo** [comment]
> Maybe just rename `file_size_in_bytes` to `total_file_size_in_bytes`?
+1

**Comment by JingsongLi** [comment]
You need to modify code not just documentation.

**Comment by MonsterChenzhuo** [comment]
> You need to modify code not just documentation.

done.

> You need to modify code not just documentation.

done.

**Comment by MonsterChenzhuo** [comment]
After thinking about it, I don't think it makes much sense to change the name.

**Pull request closed without merging**
