### PR TITLE
[doc] Complement the version limit of mysql-cdc Bundled jar.

### PR DESCRIPTION
**Pull request by LinMingQiang**
### Purpose

Linked issue: close #xxx

### CODE REVIEW

**Comment by zhuangchong** [comment]
Paimon mysql cdc supports flink cdc 2.3.x and 2.4.x, but are you sure it supports 3.0.x? Have you tested it?

**Comment by LinMingQiang** [comment]
Yes, I have tested version 3.0.x and 3.1.x, version 3.0.x successfully writes data and supports schema evolution.

**Comment by zhuangchong** [comment]
Please add version 2.3.x

**Comment by LinMingQiang** [comment]
done

**Review by zhuangchong — APPROVED** [review]
+1

**Pull request merged**
