### PR TITLE
[spark]  remove the dependency of paimon-bundle in all submodules of paimon-spark.

### LINKED ISSUE #4351: [Bug] idea cannot find classes of other modules in the paimon-spark submodule.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

1.0-SNAPSHOT

### Compute Engine

spark

### Minimal reproduce step

Idea cannot find classes of other modules in the paimon-spark submodule.

### What doesn't meet your expectations?

Cannot debug paimon-spark module in idea.

### Anything else?

reason: The `paimon-spark` submodule explicitly excludes all paimon dependencies, which makes idea unable to find the paimon class.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by liming30**
### Purpose

Linked issue: close #4351

Remove the dependency of `paimon-bundle` in all submodules of `paimon-spark` to fix the problem that the paimon class cannot be found in idea.

### CODE REVIEW

**Comment by wwj6591812** [comment]
+1

**Comment by liming30** [comment]
@JingsongLi @Zouxxyy can I merge this PR?

**Comment by Zouxxyy** [comment]
I test `MigrateFileProcedureTest` on my IDEA and it throw this:

```
An exception or error caused a run to abort: COMPRESSION_ZSTD_LEVEL 
java.lang.NoSuchFieldError: COMPRESSION_ZSTD_LEVEL
	at org.apache.paimon.format.orc.OrcFileFormat.getOrcProperties(OrcFileFormat.java:152)
	at org.apache.paimon.format.orc.OrcFileFormat.<init>(OrcFileFormat.java:75)
	at org.apache.paimon.format.orc.OrcFileFormatFactory.create(OrcFileFormatFactory.java:35)
	at org.apache.paimon.format.orc.OrcFileFormatFactory.create(OrcFileFormatFactory.java:24)
	at org.apache.paimon.format.FileFormat.fromIdentifier(FileFormat.java:106)
	at org.apache.paimon.format.FileFormat.fromIdentifier(FileFormat.java:91)
```

**Comment by liming30** [comment]
> I test `MigrateFileProcedureTest` on my IDEA and it throw this:
> 
> ```
> An exception or error caused a run to abort: COMPRESSION_ZSTD_LEVEL 
> java.lang.NoSuchFieldError: COMPRESSION_ZSTD_LEVEL
> 	at org.apache.paimon.format.orc.OrcFileFormat.getOrcProperties(OrcFileFormat.java:152)
> 	at org.apache.paimon.format.orc.OrcFileFormat.<init>(OrcFileFormat.java:75)
> 	at org.apache.paimon.format.orc.OrcFileFormatFactory.create(OrcFileFormatFactory.java:35)
> 	at org.apache.paimon.format.orc.OrcFileFormatFactory.create(OrcFileFormatFactory.java:24)
> 	at org.apache.paimon.format.FileFormat.fromIdentifier(FileFormat.java:106)
> 	at org.apache.paimon.format.FileFormat.fromIdentifier(FileFormat.java:91)
> ```

@Zouxxyy There is a version conflict with `orc-core`. When I exclude it, all the tests in idea can run successfully. But when I use `mvn` to execute in the terminal, an exception occurs that orc classes cannot be found. Do you have any other suggestions?

**Comment by Zouxxyy** [comment]
> @Zouxxyy There is a version conflict with `orc-core`. When I exclude it, all the tests in idea can run successfully. But when I use `mvn` to execute in the terminal, an exception occurs that orc classes cannot be found. Do you have any other suggestions?

In fact, I have no other suitable solutions yet. Can you try 1) remove paimon-bundle, 2) exclude orc or parquet deps in spark deps 3) add orc or parquet deps with paimon used version

**Comment by Zouxxyy** [comment]
@liming30 Can you try this https://github.com/Zouxxyy/incubator-paimon/commit/05d3a86936704d5138e713b33bd93d43c829b116

**Comment by liming30** [comment]
> @liming30 Can you try this [Zouxxyy@05d3a86](https://github.com/Zouxxyy/incubator-paimon/commit/05d3a86936704d5138e713b33bd93d43c829b116)

Thanks for your help, I'll try this again later.

**Review by Zouxxyy — APPROVED** [review]

**Comment by liming30** [comment]
@Zouxxyy There are still some tests that fail in idea, such as `org.apache.paimon.spark.procedure.MigrateTableProcedureTest`. I will try to solve this problem next.

**Comment by askwang** [comment]
> @Zouxxyy There are still some tests that fail in idea, such as `org.apache.paimon.spark.procedure.MigrateTableProcedureTest`. I will try to solve this problem next.

@liming30 I tested it ok in my idea, maybe you need rebuild the project

**Comment by YannByron** [comment]
That works. +1.

**Pull request merged**
