### PR TITLE
[spark]Support get full table name include database

### PR DESCRIPTION
**Pull request by waywtdcc**
### Purpose

Support get full table name include database
ranger spark auth plugin check auth error

image

### CODE REVIEW

**Comment by Zouxxyy** [comment]
This is the define of `String name()`

```scala
  /**
   * A name to identify this table. Implementations should provide a meaningful name, like the
   * database and table name from catalog, or the location of files for this table.
   */
  String name();
```

I don't think it is a good idea for range to get database through it, because this interface is just a name and users may define it arbitrarily.

However, enriching this name helps display information in spark UI, I remember iceberg is `catalog.db.name` now.

**Comment by Zouxxyy** [comment]
This should be fixed in kyuubi range plugin

**Comment by waywtdcc** [comment]
But it's not unique if there is only one table name, which doesn't feel good.

**Comment by Zouxxyy** [comment]
> But it's not unique if there is only one table name, which doesn't feel good.

Yes, as I said before, this name will eventually be displayed in the UI, it'll be greate to like `catalog.db.name`

The current implementation requires modifying the constructor, it would be nice if the paimonTable could include it.

**Comment by Zouxxyy** [comment]
https://github.com/apache/paimon/pull/3680 focus on the same porblem and merged, sorry for that

**Comment by JingsongLi** [comment]
Fixed in:
https://github.com/apache/paimon/pull/3680
https://github.com/apache/paimon/pull/3686

**Pull request closed without merging**
