### PR TITLE
[cdc] Fix kafka canal-json cdc action cannot find confluent schema registry client class when converting dataformat

### LINKED ISSUE #3999: [Bug] org.apache.paimon.flink.action.cdc.format.DataFormat IllegalAccessError
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

In the master branch, null parameter construction is used during the initialization process of the org.apache.paimon.flink.action.cdc.format.DataFormat  class, but there is no null parameter construction method in the corresponding class；
eg:public enum DataFormat {
    CANAL_JSON(
            CanalRecordParser::new,
            KafkaDebeziumJsonDeserializationSchema::new,
            CdcJsonDeserializationSchema::new),
    OGG_JSON(
            OggRecordParser::new,
            KafkaDebeziumJsonDeserializationSchema::new,
            CdcJsonDeserializationSchema::new),
    MAXWELL_JSON(
            MaxwellRecordParser::new,
            KafkaDebeziumJsonDeserializationSchema::new,
            CdcJsonDeserializationSchema::new),
    DEBEZIUM_JSON(
            DebeziumJsonRecordParser::new,
            KafkaDebeziumJsonDeserializationSchema::new,
            CdcJsonDeserializationSchema::new),
    DEBEZIUM_AVRO(
            DebeziumAvroRecordParser::new,
            KafkaDebeziumAvroDeserializationSchema::new,
            PulsarDebeziumAvroDeserializationSchema::new),
    JSON(
            JsonRecordParser::new,
            KafkaDebeziumJsonDeserializationSchema::new,
            CdcJsonDeserializationSchema::new);

### Compute Engine

flink1.7.2

### Minimal reproduce step

coding error org.apache.paimon.flink.action.cdc.format.DataFormat

### What doesn't meet your expectations?

java.lang.IllegalAccessError: no such constructor: org.apache.paimon.flink.action.cdc.kafka.KafkaDebeziumAvroDeserializationSchema

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhuangchong**
### Purpose

this pr closes #3999 

Fix kafka canal-json cdc action cannot find confluent schema registry client class when converting dataformat.

exception:
image

### CODE REVIEW

**Review by JingsongLi — COMMENTED** [review]
Why this fix works?

**Comment by zhuangchong** [comment]
> Why this fix works?

Sorry, I can't answer this question well.

I know this is a problem related to class loading. Since the DataFormat enumeration will load all enumeration instances during initialization, the JVM will try to load the KafkaDebeziumJsonDeserializationSchema class.

The implementation class CachedSchemaRegistryClient of io.confluent.kafka.schemaregistry.client.SchemaRegistryClient is introduced in the KafkaDebeziumJsonDeserializationSchema class.

The exception stack is as follows:
image


When I put the CachedSchemaRegistryClient in the KafkaDebeziumJsonDeserializationSchema class into the ConfluentAvroDeserializationSchema tool class, there was no exception in the local test.

**Comment by JingsongLi** [comment]
@zhuangchong Can you describe the whole reproducing steps? I cannot find which local test case in the context.

**Comment by zhuangchong** [comment]
> @zhuangchong Can you describe the whole reproducing steps? I cannot find which local test case in the context.

According to issue #3999, the steps to reproduce are as follows:

Project Module: paimon-flink-action
Run the main method `org.apache.paimon.flink.action.FlinkActions` in idea

Main Arguments : 
kafka_sync_database --warehouse file:///tmp/paimon --database ods_db --table_prefix ods_common_ --kafka_conf properties.bootstrap.servers=DT-US-dev-bg-kafka-01:9092,DT-US-dev-bg-kafka-02:9092,1DT-US-dev-bg-kafka-03:9092 --kafka_conf topic=MONITOR_COMMON_TOPIC --kafka_conf properties.group.id=group_ods_cwl_datacenter --kafka_conf scan.startup.mode=earliest-offset --kafka_conf value.format=canal-json  --table_conf bucket=4 --table_conf changelog-producer=input --table_conf sink.parallelism=1 --table_conf metastore.partitioned-table=true

Add dependencies to paimon-flink-action pom file: 
```
<dependencies>
        <dependency>
            <groupId>org.apache.paimon</groupId>
            <artifactId>paimon-flink-common</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.paimon</groupId>
            <artifactId>paimon-flink-cdc</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kafka</artifactId>
            <version>3.0.1-1.18</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-runtime</artifactId>
            <version>1.18.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-planner-loader</artifactId>
            <version>1.18.1</version>
            <scope>provided</scope>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>org.apache.flink</groupId>-->
        <!--            <artifactId>flink-table-planner_2.12</artifactId>-->
        <!--            <version>${flink.version}</version>-->
        <!--            <scope>provided</scope>-->
        <!--        </dependency>-->


        <dependency>
            <groupId>org.apache.paimon</groupId>
            <artifactId>paimon-hive-connector-3.1</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-cli</artifactId>
            <version>2.3.10</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-mapreduce-client-core</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>log4j</artifactId>
                    <groupId>log4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <artifactId>hadoop-hdfs</artifactId>
            <groupId>org.apache.hadoop</groupId>
            <version>${hadoop.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>${hadoop.version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>jdk.tools</groupId>
                    <artifactId>jdk.tools</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-mapreduce-client-core</artifactId>
            <version>${hadoop.version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>jdk.tools</groupId>
                    <artifactId>jdk.tools</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
```
image

**Comment by JingsongLi** [comment]
I understand what you mean. There indeed are some unnecessary dependencies here, but your modifications are too uncertain.

Could you directly abstract the format into a Java SPI, so that it can provide strong guarantees.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
