### PR TITLE
 Compatible with Spark4

### PR DESCRIPTION
**Pull request by awol2005ex**
Compatible with Spark4

### CODE REVIEW

**Review by JingsongLi — CHANGES_REQUESTED** [review]
Hi @awol2005ex 
We should avoid copying files.

**Comment by awol2005ex** [comment]
> Hi @awol2005ex We should avoid copying files.

主要是要改的scala太多了

**Comment by JingsongLi** [comment]
> > Hi @awol2005ex We should avoid copying files.
> 
> 主要是要改的scala太多了

Please use English (This is Apache's rule)

**Comment by JingsongLi** [comment]
You can discuss this in dev mail list. We can figure out how to support Spark 4.0.

**Comment by JingsongLi** [comment]
The changes are so huge... We should find a easy way.

**Pull request closed without merging**
