### PR TITLE
[filesystems] Supported Tencent Cloud COS filesystem

### PR DESCRIPTION
**Pull request by chenxi0599**
### Purpose

Linked issue: close #xxx

### CODE REVIEW

**Comment by chenxi0599** [comment]
I have passed the test on my own computer, using Tencent cos to read and write data

**Comment by JingsongLi** [comment]
Hi @chenxi0599 , can you explain the difference between using s3 interface and using cos interface? Both can support Tencent Cloud COS filesystem.

**Comment by chenxi0599** [comment]
Certainly, most object storage services are compatible with the S3 interface, including Aliyun OSS. However, I believe utilizing each object storage's native API would be a better choice. I have also compared accessing COS using both S3 SDK and COS SDK, and I feel that the performance with COS SDK is slightly better. Additionally, utilizing COS SDK allows for better representation of error messages returned by the server in the logs.

**Comment by chenxi0599** [comment]
> Hi @chenxi0599 , can you explain the difference between using s3 interface and using cos interface? Both can support Tencent Cloud COS filesystem.

I've searched extensively for an answer to this question but haven't found one yet.  
I believe it's preferable to use Tencent Cloud COS's native interface whenever possible, as they may have optimized it for their specific platform.  I've also compared accessing COS using both the S3 SDK and COS SDK, and it seems like the performance is slightly better with the COS SDK.  Additionally, error messages returned by the server are better reflected in the logs when using the COS SDK.

**Comment by JingsongLi** [comment]
Hi @chenxi0599 , I contacted the engineers of tencent cloud, it looks like it is OK to use S3 SDK to connect tencent COS. We can wait for more information.

**Pull request closed without merging**
