### PR TITLE
[doc] Improve partition mark done action type documentation

### PR DESCRIPTION
**Pull request by zhuangchong**
### Purpose

Improve partition mark done action type documentation

### CODE REVIEW

**Review by JingsongLi — CHANGES_REQUESTED** [review]
Hi @zhuangchong , we still don't know the usage of `mark-event`, I think it is good to keep it not in documentation.

**Comment by zhuangchong** [comment]
> Hi @zhuangchong , we still don't know the usage of `mark-event`, I think it is good to keep it not in documentation.

The `mark-event` is to mark the partition completion by the `markPartitionForEvent` method provided by the hive metastore client.

 Then use the hive metastore client's isPartitionMarkedForEvent method to query whether the partition is completed.

image

**Review by JingsongLi — APPROVED** [review]
+1

**Comment by JingsongLi** [comment]
> > Hi @zhuangchong , we still don't know the usage of `mark-event`, I think it is good to keep it not in documentation.
> 
> The `mark-event` is to mark the partition completion by the `markPartitionForEvent` method provided by the hive metastore client.
> 
> Then use the hive metastore client's isPartitionMarkedForEvent method to query whether the partition is completed.
> 
> image

Make sense, merging...

**Pull request merged**
