### PR TITLE
[Core] Optimize Parquet Reading by Enhancing Predicate Pushdown to the Page Level

### PR DESCRIPTION
**Pull request by Aiden-Dong**
### Purpose

Linked issue: [#4586](https://github.com/apache/paimon/issues/4586)

### CODE REVIEW

**Comment by JingsongLi** [comment]
This modification is not that simple, it requires us to modify the column reader.

**Comment by Aiden-Dong** [comment]
> 这个修改没那么简单，它需要我们修改列阅读器。

I found that it works in my local tests, and the column pages obtained based on FilterRowGroup are filtered. Is there any error I might have missed?

**Comment by Aiden-Dong** [comment]
> This modification is not that simple, it requires us to modify the column reader.

I found that it works in my local tests, and the column pages obtained based on FilterRowGroup are filtered. Is there any error I might have missed?

**Comment by Aiden-Dong** [comment]
In my local tests, I found that with 4 million rows and 3 columns (3 files), after 30 random reads, the time dropped from 14s to 1.9s, and the correct results were returned.

**Comment by JingsongLi** [comment]
https://github.com/apache/paimon/pull/3610

**Comment by JingsongLi** [comment]
See implementation in Spark.

**Comment by JingsongLi** [comment]
Close this now, feel free to re-open if you have more questions.

**Comment by Aiden-Dong** [comment]
> See implementation in Spark.

ok tks, I'll go check how parquet is implemented when reading in Spark.

**Pull request closed without merging**
