### PR TITLE
[cdc] Add flink execution mode check for cdc table sync action.

### PR DESCRIPTION
**Pull request by LinMingQiang**
### Purpose

Linked issue: close #xxx

Flink-cdc do not support batch mode, including flink cdc `snapshot` scan mode . Although it is a bounded source.

https://issues.apache.org/jira/browse/FLINK-36280

https://github.com/apache/flink-cdc/pull/2901

if use set RuntimeExecutionMode = Batch. job will be never finish and never fail.

image

so , we need to check the flink execution mode.

### CODE REVIEW

**Comment by LinMingQiang** [comment]
If this change is acceptable, I will complete the other actions / mongodb/Postgres.

**Comment by wwj6591812** [comment]
Do we need to handle RuntimeExecutionMode.AUTOMATIC?

**Comment by wwj6591812** [comment]
Do we need to handle RuntimeExecutionMode.AUTOMATIC?

**Comment by LinMingQiang** [comment]
> Do we need to handle RuntimeExecutionMode.AUTOMATIC?

yes need too, may be we can make STREAMING mode as default and ignore the user's settings.

**Comment by LinMingQiang** [comment]
@yuzelin Help me check this pr?  tks.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
