### PR TITLE
[core][spark] Support adding and dropping nested columns in Spark

### PR DESCRIPTION
**Pull request by tsreaper**
### Purpose

Spark SQL supports adding and dropping nested columns, but Paimon currently does not support it. This PR adds support for adding and dropping nested columns.

### Tests

Unit tests and IT cases.

### API and Format

No format changes.

### Documentation

This feature does not need a document.

### CODE REVIEW

**Comment by JingsongLi** [comment]
Try to support this in Flink SQL too:
```
Flink SQL> create table s1 (a int, nc row<f1 int, f2 string> ) with ('connector'='datagen', 'number-of-rows'='10');
[INFO] Execute statement succeed.

Flink SQL> alter table s1 modify nc row<f1 int, f2 string, f3 string>;
[INFO] Execute statement succeed.
```

**Comment by tsreaper** [comment]
> Try to support this in Flink SQL too:
> 
> ```
> Flink SQL> create table s1 (a int, nc row<f1 int, f2 string> ) with ('connector'='datagen', 'number-of-rows'='10');
> [INFO] Execute statement succeed.
> 
> Flink SQL> alter table s1 modify nc row<f1 int, f2 string, f3 string>;
> [INFO] Execute statement succeed.
> ```

Let's implement this in another PR.

**Review by JingsongLi — COMMENTED** [review]
Please add doc too

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
