### PR TITLE
[spark] drop partition when all the conditions is partition-related

### PR DESCRIPTION
**Pull request by YannByron**
### Purpose

Linked issue: close #xxx

### CODE REVIEW

**Comment by JingsongLi** [comment]
Which Test can cover this modification?

**Comment by YannByron** [comment]
> Which Test can cover this modification?

no new cases. I've tested the case `Paimon Delete: append-only table with partition` in `DeleteFromTableTest` and check the code path when execute.

**Comment by JingsongLi** [comment]
> > Which Test can cover this modification?
> 
> no new cases. I've tested the case `Paimon Delete: append-only table with partition` in `DeleteFromTableTest` and check the code path when execute.

I see, `DELETE FROM T WHERE dt IN ('2026', '2027')` will use partition dropping now.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
