### PR TITLE
[cdc] Support debezium avro format

### PR DESCRIPTION
**Pull request by harveyyue**
### Purpose

Linked issue: close #xxx

### CODE REVIEW

**Comment by harveyyue** [comment]
Can someone enable the CI test?

**Comment by wg1026688210** [comment]
https://github.com/harveyyue/incubator-paimon/tree/dbz-format
@harveyyue This will show the result of CI

**Comment by yuzelin** [comment]
Hi, can you solve the conflicts?

**Comment by yuzelin** [comment]
Seem this PR is not active now. I will continue to work on it.

**Comment by umeshdangat** [comment]
I was trying to test consuming debezium avro data using this branch. I found that it needed support for some complex types. I made changes here: https://github.com/harveyyue/incubator-paimon/pull/1/files

Not sure if they are appropriate as I had to change TypeUtils to handle complex types as well.

**Comment by yuzelin** [comment]
@umeshdangat I'm working on merging these codes into the master branch. When it is done, you can create a PR to support your needed types.

**Comment by harveyyue** [comment]
@yuzelin

**Comment by yuzelin** [comment]
@harveyyue Glad to hear from you! I just start to this. It's good if you are willing to continue to work on this.

**Comment by umeshdangat** [comment]
@yuzelin @harveyyue  checking in to see if this is going to be picked up soon?

**Comment by polyzos** [comment]
@JingsongLi can you help merge this?

**Comment by JingsongLi** [comment]
Thanks @harveyyue for the contribution and all for your attention!

**Pull request closed without merging**
