### PR TITLE
[flink] Manage flink version for paimon-flink-common and paimon-flink-cdc

### LINKED ISSUE #2141: [Feature] Manage flink version for paimon-flink-common and paimon-flink-cdc
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Manage flink version for paimon-flink-common and paimon-flink-cdc

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by FangYongs**
### Purpose

Linked issue: close #2141 

Manage flink version

### Tests

This feature is covered by existing tests

### API and Format

no

### Documentation

no

### CODE REVIEW

**Comment by yuzelin** [comment]
The problem is that flink-kafka-connector will be removed from flink-1.18 repo, so the 1.18-snapshot kafka connector are outdate. We should wait for the flink-1.18 release and then modify the POM.

**Comment by FangYongs** [comment]
> The problem is that flink-kafka-connector will be removed from [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18 repo, so the 1.18-snapshot kafka connector are outdate. We should wait for the [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18 release and then modify the POM.

Get it. I think we may need to split flink-cdc to sub modules like paimon-flink-cdc-common, paimon-flink-cdc-1.17 and paimon-flink-cdc-1.18. WDYT?

**Comment by JingsongLi** [comment]
> > The problem is that flink-kafka-connector will be removed from [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18 repo, so the 1.18-snapshot kafka connector are outdate. We should wait for the [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18 release and then modify the POM.
> 
> Get it. I think we may need to split flink-cdc to sub modules like paimon-flink-cdc-common, paimon-flink-cdc-1.17 and paimon-flink-cdc-1.18. WDYT?

No, it is not the good, it is hard to maintain another Flink versions...

**Comment by yuzelin** [comment]
> > > The problem is that flink-kafka-connector will be removed from [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18 repo, so the 1.18-snapshot kafka connector are outdate. We should wait for the [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18 release and then modify the POM.
> > 
> > 
> > Get it. I think we may need to split flink-cdc to sub modules like paimon-flink-cdc-common, paimon-flink-cdc-1.17 and paimon-flink-cdc-1.18. WDYT?
> 
> No, it is not the good, it is hard to maintain another Flink versions...

I agree.

**Comment by FangYongs** [comment]
@JingsongLi @yuzelin Then how can we maintain cdc for different flink versions? such as flink-1.17 and flink-1.18? If we create paimon-flink-cdc-common, paimon-flink-cdc-1.17 and paimon-flink-cdc-1.17 like paimon-flink-xxx, users can pick the right flink-cdc version as they need

**Comment by yuzelin** [comment]
> @JingsongLi @yuzelin Then how can we maintain cdc for different flink versions? such as [flink-1](https://issues.apache.org/jira/browse/FLINK-1).17 and [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18? If we create paimon-flink-cdc-common, paimon-flink-cdc-1.17 and paimon-flink-cdc-1.17 like paimon-flink-xxx, users can pick the right flink-cdc version as they need

Actually, the cdc submodule will be shaded to the paimon-flink-<version> jar, and users don't need to download the cdc jar.

**Comment by yuzelin** [comment]
FYI, flink-kafka-connector 3.0.1 (for flink 1.18) will be released soon (VOTE: https://lists.apache.org/thread/35gjflv4j2pp2h9oy5syj2vdfpotg486).
After that we can update cdc module dependencies.

**Pull request closed without merging**
