### PR TITLE
[doc] Add a Chinese version for the documentation

### PR DESCRIPTION
**Pull request by Waterkin**
### Purpose

Linked issue: open #2708 

Add a Chinese version for the documentation, while new Chinese files (stored in `docs/content.zh`) are still the same in English (stored in `docs/content`), needing further translation.

### CODE REVIEW

**Review by JingsongLi — CHANGES_REQUESTED** [review]
Hi @Waterkin 

Do not just copy all documentation files. We should do translation one by one.

**Comment by Waterkin** [comment]
Hi @JingsongLi 

I've added an entrance to the new Chinese version at the sidebar, so people can simply focus on the translations of English content at `docs/content.zh`. For example, people can just revise these contents and submit a PR online, making translations more convenient. The convenience will make translation, which is a huge work, easier.

**Comment by JingsongLi** [comment]
> Hi @JingsongLi
> 
> I've added an entrance to the new Chinese version at the sidebar, so people can simply focus on the translations of English content at `docs/content.zh`. For example, people can just revise these contents and submit a PR online, making translations more convenient. The convenience will make translation, which is a huge work, easier.

Do not copy without translation which makes maintenance very difficult, and the result is not yet any benefit.

**Comment by Waterkin** [comment]
@JingsongLi Do you think it ok that I delete the copyed files and only translate some of them?

**Comment by JingsongLi** [comment]
> @JingsongLi Do you think it ok that I delete the copyed files and only translate some of them?

Yes, that is a better way.

**Comment by Waterkin** [comment]
@JingsongLi PTAL, thanks!

**Comment by JingsongLi** [comment]
Hi @Waterkin , very thanks for your contribution.

But it is really hard to maintain two documentation. It is recommended to use translator to read english documentation.

**Pull request closed without merging**
