### PR TITLE
[flink] mongodb into the lake related code optimized

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
### Purpose

Add mongodb into the lake related code comments and optimize the code logic.

### Documentation
cdc ingestion

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
@yuzelin  Could you please restart the CI for me? Thanks!

**Comment by yuzelin** [comment]
Please rebase the master branch. We have made some efforts to solve the timeout problem.

**Comment by MonsterChenzhuo** [comment]
> Please rebase the master branch. We have made some efforts to solve the timeout problem.

done.

**Comment by MonsterChenzhuo** [comment]
@yuzelin  PTAL,thanks.

**Comment by JingsongLi** [comment]
Please rebase master.

**Comment by MonsterChenzhuo** [comment]
> Please rebase master.

done.

**Pull request merged**
