### PR TITLE
[hive] add hive client pool

### PR DESCRIPTION
**Pull request by zhuangchong**
### Purpose

add hive client pool

### CODE REVIEW

**Comment by XuQianJin-Stars** [comment]
hi @zhuangchong Is there any difference between this PR and https://github.com/apache/incubator-paimon/pull/2567 ?The e2e test has been unstable before.

**Comment by zhuangchong** [comment]
> hi @zhuangchong Is there any difference between this PR and #2567 ?The e2e test has been unstable before.

There is no difference. PR 2567 has not been updated for a long time, and this feature is very needed, so I launched a PR again, merging the latest code and solving the UT exception.

If you have time and are willing to update PR 2567, I can close this PR. @XuQianJin-Stars

**Comment by XuQianJin-Stars** [comment]
> > hi @zhuangchong Is there any difference between this PR and #2567 ?The e2e test has been unstable before.
> 
> There is no difference. PR 2567 has not been updated for a long time, and this feature is very needed, so I launched a PR again, merging the latest code and solving the UT exception.
> 
> If you have time and are willing to update PR 2567, I can close this PR. @XuQianJin-Stars

I understand. I don't care about this PR merge. I will close PR 2567. The reason I left a comment is to tell me you want to use this PR 2567.

**Comment by caicancai** [comment]
@zhuangchong I think it's ok to add XuQianJin-Stars as co-author

**Comment by zhuangchong** [comment]
> hi @zhuangchong I think it's ok to add XuQianJin-Stars as co-author

Where is this added?

**Comment by caicancai** [comment]
> For this situation, I think you can make changes based on the original pr and then push the modified code to the original author's repository

Add co-author information in the commit message

**Comment by JingsongLi** [comment]
Hi @zhuangchong 
What is the status? I remember passing the test? What have you done now?

**Comment by zhuangchong** [comment]
> Hi @zhuangchong What is the status? I remember passing the test? What have you done now?

@JingsongLi I merged the latest code, and then ut error package cannot be found, I am looking for the problem.

**Comment by JingsongLi** [comment]
@zhuangchong You mean you just cherry-picked https://github.com/apache/paimon/pull/2567 ? Why not kust keep your code?

**Comment by zhuangchong** [comment]
> @zhuangchong You mean you just cherry-picked #2567 ? Why not kust keep your code?

The CI is experiencing anomalies after merging the latest code into the master branch.

**Comment by sunxiaojian** [comment]
Is CachedClientPool considering creating an abstraction layer? JdbcClientPool may also need to be implemented through caching

**Comment by JingsongLi** [comment]
Sorry for the late reply.

I've been thinking for a long time, why do we need a client pool? Are there any user needs?

**Comment by zhuangchong** [comment]
> Sorry for the late reply.
> 
> I've been thinking for a long time, why do we need a client pool? Are there any user needs?

A user reported that Paimon uses hive catalog, and the number of hive metastore connections exceeds 10,000.
image

**Comment by waywtdcc** [comment]
> > Sorry for the late reply.
> > I've been thinking for a long time, why do we need a client pool? Are there any user needs?
> 
> A user reported that Paimon uses hive catalog, and the number of hive metastore connections exceeds 10,000. image

+1

**Comment by JingsongLi** [comment]
Sorry, I can't understand why this PR can solve the connection count problem. I understand that the hive connection count problem is just because you didn't close the catalog?

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
