### PR TITLE
[core] Check the validity of scan staring snapshotId

### PR DESCRIPTION
**Pull request by LinMingQiang**
…correct exception.

### Purpose

Linked issue: close #xxx

### CODE REVIEW

**Comment by leaves12138** [comment]
This pull request should not effect scan between timestamp...

**Comment by LinMingQiang** [comment]
Based on my understanding ,because of the left open right closed rule of ` IncrementalStartingScanner` that is different from `StaticFromStartingScanner`, we should allow starting snapshotId is equal earliestSnapshotId - 1 like 0.

**Comment by LinMingQiang** [comment]
@JingsongLi Help to review this PR, thanks.

**Review by leaves12138 — APPROVED** [review]
+1

**Pull request merged**
