### PR TITLE
[core] Fix merge schemas equal method issue

### PR DESCRIPTION
**Pull request by harveyyue**
### Purpose

Linked issue: close #xxx
No

### CODE REVIEW

**Comment by wwj6591812** [comment]
+1

**Comment by JingsongLi** [comment]
I remember this is not an issue. @harveyyue Can you find the exact case?

**Comment by JingsongLi** [comment]
> > I remember this is not an issue. @harveyyue Can you find the exact case?
> 
> Using spark format `paimon` to write upstream data will generate a new schema-xxx since have no schema changes `dataset.format("paimon").options(options);`

@harveyyue Can you add a test case?

**Comment by harveyyue** [comment]
> > > I remember this is not an issue. @harveyyue Can you find the exact case?
> > 
> > 
> > Using spark format `paimon` to write upstream data will generate a new schema-xxx since have no schema changes `dataset.format("paimon").options(options);`
> 
> @harveyyue Can you add a test case?

Done
We did some changes to reselect column according table schema, so we will trigger the `==` compare method from row type.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
